name: Notify Discord on Push

on:
  push:
    branches:
      - feature-g2/63-cd-discord 

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Send Discord notification
        uses: Ilshidur/action-discord@0.4.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ðŸ“¢ **New push to branch:** `${{ github.ref_name }}`
            ðŸ‘¤ **Author:** ${{ github.actor }}
            ðŸ“„ **Commit:** ${{ github.event.head_commit.message }}
            ðŸ”— <${{ github.event.head_commit.url }}>
