# ----------------------------------------------------------------------------
# Publish image in Docker Hub Workflow
# This workflow builds and pushes a Docker image to Docker Hub whenever
# a push is made to main-2
# ----------------------------------------------------------------------------

name: Publish main-2 image in Docker Hub

on:
  push:
    branches:
      - main-2
      - feature-g2/61-cd-docker-deployment-main-2

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04

    env:
      MASTER_KEY: ${{ secrets.MASTER_KEY }}
      BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
      ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
      ELASTICSEARCH_USER: ${{ secrets.ELASTICSEARCH_USER }}
      ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}

    steps:
      
      # Step 1: Check out the repository code
      - uses: actions/checkout@v5

      # Step 2: Log in to Docker Hub using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER_2 }}
          password: ${{ secrets.DOCKER_PASSWORD_2 }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        run: |
          TAG=${{ github.event.release.tag_name || github.sha }}
          IMAGE=${{ secrets.DOCKER_USER_2 }}/foodhub2

          docker build --build-arg VERSION_TAG=$TAG -t $IMAGE:$TAG -f docker/images/Dockerfile.prod .
          docker push $IMAGE:$TAG

          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest
